### ISSUE TITLE
Is the code functional ?

### ISSUE THREAD

**Issue by mr-sneezy** [hardtechnology/efergy_v2#1]
Hi mate (fellow Aussie). I have a Efergy E2 installed on my home and I run HA with Mosquito broker. Currently the Efergy E2 is stand alone.
I'm keen to hack the Efergy receiver if this code is functional, can you confirm that, or is it not that mature/tested yet ?

If it is then I can do the rest.
Cheers from Adelaide

**Comment by steven-geo** [comment]
Hi, yeah, should be good to go. I have been running this 24/7 for most of a year, I haven't compiled it in a while though.

**Comment by mr-sneezy** [comment]
OK, I have a another project to do now :)
