### ISSUE TITLE
Single Phase or Three Phase compatible ?

### ISSUE THREAD

**Issue by mr-sneezy** [hardtechnology/efergy_v2#2]
I'm looking at the code (which is a bit advanced for me to be frank).

I can't determine if the code can decode one or three phase data bytes as it is now ?
My Efergy E2 is connected to three phases...

**Comment by steven-geo** [comment]
I believe this model of Efergy combines all 3 phases into a single value - so you can't access the individual phases. See how you go. Some of the older models (this is not written for them), had separate readings for each phase from the transmitter.

**Comment by mr-sneezy** [comment]
Happy to try.
Hey I know it's a bit against the grain of code sharing, but since the code is for a ESP8266 board and quite generic could you post your last binary file I could flash it for a test ?
I think the networking parameters are entered from AP mode after boot so should work (not sure).

**Comment by steven-geo** [comment]
I think sharing a binary is probably more trouble than it's worth. Checkout the Arduino environment and pull down the latest.
