### ISSUE TITLE
ArduinoJson version errors on compile

### ISSUE THREAD

**Issue by mr-sneezy** [hardtechnology/efergy_v2#3]
Had a crack at compilation.
Getting multiple errors about ArduinoJson versions. Apparently a library downgrade or code migration needed.
```
error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
     DynamicJsonBuffer jsonBuffer;

```

**Comment by steven-geo** [comment]
Looks like you may have an old version of ArduinoJson library. This is compiled with version 5.8.0. I will take a look at upgrading to the 6.x versions in the future.

**Comment by mr-sneezy** [comment]
Had a look in the libraries folder. My version is "version=6.16.1".

**Comment by steven-geo** [comment]
Hi, Please pull the master branch again. I have just updated and it compiles with the newest ArduinoJson Library 6.18.3

**Comment by mr-sneezy** [comment]
Thanks that sorted it. 
Confirmed it compiles in Arduino 1.8.15.

Also compiled in 2.0.0-beta10, but had one warning, about a type issue in efergy.cpp

Will try it out connected on the E2 this week soon.

**Comment by steven-geo** [comment]
Can you let me know more about the type error? I compile without any errors on Arduino 1.8.15 as well, so must be a library update. Thanks

**Comment by mr-sneezy** [comment]
I re-ran the 2.0.0-beta10 compiler tonight and the warning error has not repeated. I guess a shut down restart on the PC has sorted out something...
