### ISSUE TITLE
Receiver power bypass link required ?

### ISSUE THREAD

**Issue by mr-sneezy** [hardtechnology/efergy_v2#5]
I'm wiring up between the E2 unit and the ESP8266. 
Relating to the image on the old versions Git page for the E2 receiver connection point, is the link to bypass power control for the RX chip required if you only have one Efergy TX unit ?

I'm thinking that it may not be needed in that usage case...

**Comment by steven-geo** [comment]
It might, but it cycles the power on to the Reciver only when it is expecting a packet. If I recall, when removing power it will need re-syncing. It might work with a single receiver. You are welcome to try without the bypass.
